version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=focusflow_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JAVA_HOME=/usr/lib/jvm/msopenjdk-current
      - PATH=/usr/lib/jvm/msopenjdk-current/bin:${PATH}
    depends_on:
      - db
    networks:
      - focusflow-network
    user: vscode
    init: true
    entrypoint: ["/bin/sh", "-c", "chmod +x /workspace/.devcontainer/init-project.sh && exec sleep infinity"]

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=focusflow_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - focusflow-network

networks:
  focusflow-network:
    driver: bridge

volumes:
  postgres-data:
